# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '98aee90d-59c1-4b88-8ebe-e68c2d92fd0f'
  imageRepository: 'whitespacemxgsspringbootdocker'
  containerRegistry: 'demojava.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'demojava2eca-auth'
  vmImageName: 'ubuntu-latest'

- stage: Build 
  - task: Bash@3
    displayName: Build container images for each service
    inputs:
      targetType: 'inline'
      script: |
        export CONTAINER_REGISTRY=$(CONTAINER_REGISTRY)
        export IMAGE_TAG=$(IMAGE_TAG)
        echo 'Install ACR  credential helper and login'
        az acr login -n $(CONTAINER_REGISTRY)
        docker login -u $(AZURE-REGISTRY-USERNAME) -p $(AZURE-REGISTRY-PASSWORD) $(CONTAINER_REGISTRY).azurecr.io
        echo 'Start Build'
        cd config
        mvn compile jib:build \
            -Djib.container.environment=CONFIG_SERVICE_PASSWORD=$(CONFIG-SERVICE-PASSWORD) 
        echo 'Build complete'